spring:
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/shared
        git:
          uri: https://github.com/forezp/SpringcloudConfig
          search-paths: respo
          username: miles02@163.com
          password:
      label: master
  application:
    name: config-server
#  profiles:
#    active: native

server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/